linters:
  enable-all: true
  disable:
    - nonamedreturns
    - structcheck
    - exhaustruct
    - varnamelen
    - depguard
    - ireturn
  fast: false

output:
  format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true
